apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-component  # Replace with the rendered value of `values.component_id`
  description: ${{ values.description | dump }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
